#!/bin/bash

devel1=Thor
devel2=Magnus
validChoice=0

echo "Welcome to $devel1 and $devel2 software installer"
echo
echo Please input the full name of the package to be installed[Enter]
read pckNm

while [ $validChoice -eq 0 ]
do
  echo Install software from sourcecode press 1
  echo Install software from dpkg/rpm press 2
  echo
  echo 1 or 2[Enter]:
  read choice
	
  if [ $choice = "1" ]; then
    validChoice=1
    echo "using sourcecode"
  elif [ $choice = "2" ]; then
    validChoice=1
    echo "using dpkg/rpm "
  else
    echo bad input
  fi
done
