#!/bin/bash

devel1=Thor
devel2=Magnus
validChoice=0
privilegeChanged=0
CYAN='\033[0;36m'
RED='\033[0;31m'

echo
echo -----------------------------------------------------------------
echo -e "${CYAN}Install from Source Code:"
tput sgr0
echo ------------------------------------------------------------------
echo
#Asking user to choose package source

tput sgr0
#Prompting for direkt link
echo Please input direkt link to package[Enter]
read directLink
export directLink

perm=$(stat -c %A /usr/local/src | cut -b 9)

if [ $perm = "-" ]; then
	priviligeChanged=1
	echo -e "${CYAN}Missing write privilege for /usr/local/src"
	echo 'setting up permission'
	chmod o+w /usr/local/src
	tput sgr0
fi  



MatchingPkg=$(dpkg-query -l $pkgNm) #query installed packages
exitCode=$? #checking exitcode to see if package is known, exit code 0 is for good query
#echo $exitCode
#echo $MatchingPkg
echo
if [ $exitCode = 0 ]; then
  isInstalled=$(echo $MatchingPkg | grep ii -o -w| wc -w)
  #echo $isInstalled
  if [ $isInstalled -eq 0 ]; then
    echo -e "${CYAN}package recognised, and it is not yet installed"
  else
    echo -e "${RED}package already installed"
    exit 0
  fi
else
  echo -e "${CYAN}Unknown package... ... ..." 
fi
export pkgNm
echo  -e "${CYAN}proceeding with installation"
echo 
echo
tput sgr0
  else
    echo -e "${RED}bad input"
tput sgr0
  fi
done



#Decompress the downloaded tarball
echo  -e "${CYAN}Decompressing the downloaded tarball.."
bzip2 -cd <PACKAGE_NAME>.tar.bz2


#Change into the newly created directory
cd usr/local/src/<PACKAGE_NAME>


#Configure the build system
echo  -e "${CYAN}configure: creating ./config.status.."
./configure
 
#Build package
echo  -e "${CYAN}Building package.."
make

#Become a privileged user for system-wide install
su root


#Install package
echo  -e "${CYAN}Installing the package.."
make install


echo  -e "${CYAN}Package installed!"


