#!/bin/bash

devel1=Thor
devel2=Magnus
validChoice=0
privilegeChanged=0
CYAN='\033[0;36m'
RED='\033[0;31m'

echo
echo -----------------------------------------------------------------
echo -e "${CYAN}Install from Source Code:"
tput sgr0
echo ------------------------------------------------------------------
echo
#Asking user to choose package source

tput sgr0
read directLink
export directLink

echo $directLink
wget $directLink -P /usr/local/src

#Decompress the downloaded tarball
echo  -e "${CYAN}Decompressing the downloaded tarball.."
tput sgr0
bzip2 -cd <PACKAGE_NAME>.tar.bz2


#Change into the newly created directory
cd usr/local/src/<PACKAGE_NAME>


#Configure the build system
echo  -e "${CYAN}configure: creating ./config.status.."
tput sgr0
./configure
 
#Build package
echo  "$Building package.."
tput sgr0
make

echo $make
exitCode=$?

if [ $exitCode = "0" ]; then #make succesfull
	echo "Build was successfull! Proceeding.."
	tput sgr0
elif [ $exitCode = "1" ]; then #make failed
	echo -e "${RED}Something went wrong, trying to sovle dependencies"


#Become a privileged user for system-wide install
su root


#Install package
echo  -e "${CYAN}Installing the package.."
tput sgr0
make install

echo $make
exitCode=$?

if [ $exitCode = "0" ]; then #make install succesfull
	echo  "Package installed!"
	tput sgr0
elif [ $exitCode = "1" ]; then #make install failed
	echo -e "${RED}Something went wrong, installation failed"
	tput sgr0
fi





